############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About me"
url = "/about"
weight = 2

[[main]]
parent = "About me"
name = "My Research"
url = "/about/about_me"
weight = 1

[[main]]
parent = "About me"
name = "CV"
url = "/about/cv"
Weight = 2



[[main]]
weight = 3
name = "Contact"
url ="/contact"


# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Contact"
url = "/contact"
weight = 2
